### ISSUE TITLE
Popup window doesn't show in OS X

### ISSUE THREAD

**Issue by HenriAugusto** [HenriAugusto/PD-AutoComplete-Plugin#3]
OS X Yosemite and Sierra:

1. no window opens with the tab key 
2. (pd window **does** says: Loading plugin: /Volumes/DOCS/Pd/externals/PD-AutoComplete/completion-plugin.tcl)
3. users are able to hit tab, use the arrow keys then hit enter to get some random object but the popup doesn't shows

**Comment by alessandrostone** [comment]
also on High Sierra popup is not showing :/

**Comment by HenriAugusto** [comment]
fixed in  #76e34eb
